### ISSUE TITLE
license information

### ISSUE THREAD

**Issue by KonradHoeffner** [Onto-Med/RIO#3]
I could not find any license information. I think there should be:

* a LICENSE file
* a license badge in README.md

**Comment by KonradHoeffner** [comment]
@AlexU75: I still do not see license information.

**Comment by AlexU75** [comment]
@KonradHoeffner I added a license badge in README.md. The license information is also included in the ontology file.

**Comment by KonradHoeffner** [comment]
I don't see the badge in the README.md and GitHub expects a LICENSE file. I will add a pull request.

**Comment by KonradHoeffner** [comment]
@AlexU75: Ah, the badge is in branch 1-founding-rio-with-gfo-light.
